Feat 11 formula adding
diduk001/formulas_bot pull request #2
Opened 2024-06-13 16:48 UTC by egoridze74

2024-06-13 22:49 UTC, diduk001 requested changes

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +#include <iostream>
для моделек лучше отдельную директорию создать
и в CMakeLists.txt забыл добавить
и тесты бы неплохо написать

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +#inclue <sqlite3.h>
Ж(

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.h
> +    float coef;
давай coefficient или weight для ясности

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.h
> +    Control_element(std::string name, float coef, bool is_block, float mark, std::string description);
std::string лучше передавать по const-ссылке

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.h
> +    inline size_t get_id() const;
инлайны можно в хэдер запихать

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.h
> +    std::string print() const;
давай лучше to_string

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.h
> +    void from_db(size_t id);
не очень понятное название

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.h
> +    void commit(size_t subject_id);
не очень понятное название

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +    this->id = 0;
this-> выглядит излишним

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +#include <iostream>
и в неймспейс отдельный закинуть

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +    this->mark = -1;
можно сделать std::optional тип для дефолта

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +    this->mark = -1;
тогда нулевое значение - std::nullopt

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +    this->id = 0;
а разве не случится так, что у всех элементов в БД один и тот же id

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.h
> +class Control_element
мб final его сделать?

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +        std::cout << "Failed to get element from db" << std::endl;
лучше в std::cert

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +    if (this->name == other.name && this->coef == other.coef && this->is_blocking == other.is_blocking &&
лучше переписать в духе 
```cpp
if (this->name != other.name) return false;
if ( ... ) return false;
...
return true;
```

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +std::string Control_element::print() const {
я бы JSON-like печатал

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +    sql::PreparedStatement* pstmt = conn->prepareStatement("INSERT INTO Element (name, subject_id, value, block, description) VALUES (?, ?, ?, ?, ?)");
запрос в consts

2024-06-13 22:49 UTC, diduk001 commented on include/Control_element.cpp
> +        pstmt->setUInt64(2, subject_id);
нам тут точно 64 бита надо?

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.cpp
> +bool cmp_coefs(Control_element e1, Control_element e2)
я бы в какой-нибудь отдельный файлик utils засунул

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.cpp
> +bool cmp_coefs(Control_element e1, Control_element e2)
и лучше по ссылке передавать

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.cpp
> +Formula::Formula() = default;
однострочное в .h

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.h
> +    explicit Formula(std::vector <Control_element>);
вектор по const ссылке

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.h
> +    Control_element& operator[](size_t) const;
я бы метод get сделал ([] - noexcept, .get может выбросить исключение)

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.h
> +    inline size_t get_size() const;
можно и просто size()

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.h
> +    inline std::vector <Control_element> get_elements() const;
мне кажется, лучше удалить и бегать по индексам, чтобы не копировать лишний раз вектора

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.h
> +    Control_element& operator[](size_t) const;
и возвращать, наверное, лучше const

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.h
> +    void add(Control_element);
давай push_back или append

2024-06-13 22:49 UTC, diduk001 commented on include/Formula.h
> +    std::vector<Control_element> predict(unsigned short mark) const;
не хотим mark вещественным делать?

2024-06-13 22:49 UTC, diduk001 commented on include/db_utils.h
> +    void insert_element(const std::string &name, size_t subject_id, float coef, bool is_blocking, const std::string& description) {
в соседнем пр прокомментировал
з. ы. лучше в разные пр закидывать независимые части кода (типа вот эту штуку пихнуть в тот, а в этом чисто формулу и элемент контроля)

2024-06-13 22:49 UTC, closed without merging

2024-06-14 10:11 UTC, egoridze74 commented on include/Control_element.cpp
> +        pstmt->setUInt64(2, subject_id);
Для size_t 32 бита не хватит, мне кажется

2024-06-14 10:31 UTC, egoridze74 commented on include/Control_element.cpp
> +#include <iostream>
Модельки закинул в отдельную директорию. Не совсем понял, зачем в отдельный неймспейс закидывать.

2024-06-14 10:32 UTC, egoridze74 commented on include/Control_element.cpp
> +    this->id = 0;
Вроде не должно, потому что мы при добавлении в БД id ставится автоматически, а затем мы вписываем его в this->id

2024-06-14 10:42 UTC, egoridze74 commented on include/Control_element.cpp
> +std::string Control_element::print() const {
У меня же вроде так и печатается? Или хотим, чтобы первым словом шло название поля класса (типа "name": <название>)? Я думал, что мы эту строку будем пользователю кидать, когда он захочет узнать информацию об элементе контроля, и будто бы на русском это красивее. Но если хотим на английском, то без проблем переделаю.

2024-06-14 10:46 UTC, egoridze74 commented on include/Control_element.cpp
> +        pstmt->setUInt64(2, subject_id);
*не всегда хватит

2024-06-14 11:08 UTC, egoridze74 commented on include/Control_element.cpp
> +    this->mark = -1;
не понял, зачем это и как(