Working db + models
diduk001/formulas_bot pull request #3
Opened 2024-06-15 15:17 UTC by egoridze74

P. S. Сори за такой гигантский пр. Clang-format - это чудо.

2024-06-15 16:51 UTC, diduk001 commented
Залил ненужные директории:
- .idea/
- CMakeCache.txt
- build/
- cmake_install.cmake
- cmake-build-debug/

Удали их и добавь в свой проект [.gitignore](https://git-scm.com/docs/gitignore) со следующим содержанием:
```
/cmake-build-debug/
/*.db
/.gitignore
/build/
/.idea/
CMakeCache.txt
cmake_install.cmake
```
И все остальное, что не является кодом

2024-06-15 16:51 UTC, diduk001 commented
Проверки в CI не проходят в основном из-за этого, исправь и залей новую версию

2024-06-15 20:05 UTC, diduk001 requested changes

2024-06-15 20:05 UTC, diduk001 commented on include/db_utils.h
> +static size_t insert_element(const std::string &name, size_t subject_id,
Не хотим использовать [Forward Declaration](https://en.wikipedia.org/wiki/Forward_declaration) и передавать объект по ссылке?
Либо сделать метод insert_in_db у control element

2024-06-15 20:05 UTC, diduk001 commented on include/db_utils.h
> +  int rc = sqlite3_prepare_v2(db_conn, db_queries::insert_element, -1,
Кажется, стоит проверить, что такого элемента нет

2024-06-15 20:05 UTC, diduk001 commented on include/db_utils.h
> +  return sqlite3_last_insert_rowid(db_conn);
Кажется, стоит проверить, что успешно вставили и закрыть

2024-06-15 20:05 UTC, diduk001 commented on include/db_utils.h
> +  sqlite3_step(statement);
Почему не sqlite3_exec?

2024-06-15 20:05 UTC, diduk001 commented on include/db_utils.h
> +  sqlite3_step(statement);
Почему не sqlite3_exec?

2024-06-15 20:05 UTC, diduk001 commented on include/db_utils.h
> +  sqlite3_step(statement);
Почему не sqlite3_exec?

2024-06-15 20:05 UTC, diduk001 commented on include/db_utils.h
> +  sqlite3_step(statement);
Почему не sqlite3_exec? (и ниже тоже)

2024-06-15 20:05 UTC, diduk001 commented on include/utils.h
> +bool cmp_weights(const Control_element &e1, const Control_element &e2) {
Почему не написать оператор?

2024-06-15 20:05 UTC, diduk001 commented on models/Control_element.cpp
> +    elem.set_id(sqlite3_column_int64(statement, 0));
может std::move тут используем?

2024-06-15 20:05 UTC, diduk001 commented on models/Control_element.cpp
> +        reinterpret_cast<const char*>(sqlite3_column_text(statement, 1)));
Но ведь set_name(const std::string& name)

2024-06-15 20:05 UTC, diduk001 commented on models/Control_element.cpp
> +        reinterpret_cast<const char*>(sqlite3_column_text(statement, 5)));
Но ведь  set_description(const std::string& description)

2024-06-15 20:05 UTC, diduk001 commented on models/Control_element.cpp
> +bool Control_element::operator==(const Control_element& other) const {
id не сравниваем?

2024-06-15 20:05 UTC, diduk001 commented on models/Control_element.cpp
> +  output = "Название: " + this->get_name() +
было бы прикольнее в json-like выводить
и я бы std::format использовал

2024-06-15 20:05 UTC, diduk001 commented on models/Control_element.h
> +  inline size_t get_id() const { return this->id; }
здесь можно inline не писать, оно само инлайнит в .h

2024-06-15 20:05 UTC, diduk001 commented on models/Formula.cpp
> +  this->elements = elements;
не уверен, что это так сработает - скопируется константный массив
здесь нужно либо в сторону std::move смотреть, либо как-то по-другому

2024-06-15 20:05 UTC, diduk001 commented on models/Formula.cpp
> +float Formula::evaluate() const {
вот это бы протестировать

2024-06-15 20:05 UTC, diduk001 commented on models/Formula.cpp
> +std::vector<Control_element> Formula::predict(float mark) const {
и вот сюда тесты неплохо бы написать

2024-06-15 20:05 UTC, diduk001 commented on models/Formula.h
> +class Formula {
тоже final

2024-06-15 20:13 UTC, egoridze74 commented on models/Control_element.cpp
> +  output = "Название: " + this->get_name() +
Про json-like: я хотел, чтобы мы эту строку выводили пользователю, когда он захочет проверить введённые данные, поэтому писал на русском. Если мы всё таки пишем бота на английском, то переделаю.

2024-06-15 20:28 UTC, egoridze74 commented on include/db_utils.h
> +static size_t insert_element(const std::string &name, size_t subject_id,
Лучше сделать метод у control_element, а то я этим forward declaration разрушу всё. Времени не так много осталось. Но прочитаю про неё, спасибо.

2024-06-15 21:55 UTC, egoridze74 commented on include/db_utils.h
> +  int rc = sqlite3_prepare_v2(db_conn, db_queries::insert_element, -1,
Вроде бы не нужно, ведь:
 - Мы никаким образом не меняем айди элемента контроля в БД, так что я бы добавил проверку только на "update" запрос (сейчас её добавлю);
 - В целом мы не запрещаем человеку делать элементы контроля с полями, поэтому я бы при добавлении не делал проверку на содержание идентичного элемента

2024-06-15 22:57 UTC, egoridze74 commented on models/Control_element.cpp
> +bool Control_element::operator==(const Control_element& other) const {
да хз, вообще этот оператор нигде не юзаем вроде бы, просто для полноценности сделал

2024-06-15 22:59 UTC, egoridze74 commented on models/Control_element.cpp
> +  output = "Название: " + this->get_name() +
Кстати, какой-то кек с format. Он же вроде бы в С++20 стал частью std, а у CLion пишет мне, что format в std нет(

2024-06-15 23:06 UTC, egoridze74 commented on include/utils.h
> +bool cmp_weights(const Control_element &e1, const Control_element &e2) {
Написал оператор, но теперь не уверен, как его загрузить в sort в этом фрагменте кода:

2024-06-15 23:10 UTC, egoridze74 commented on include/utils.h
> +bool cmp_weights(const Control_element &e1, const Control_element &e2) {
Вроде бы написал, но лучше перепроверь пж, может быть можно это упростить и как-то пихнуть это условие сразу туда, не создаваю файл utils (мб можно лямбда-функциями, но не уверен).

2024-06-15 23:23 UTC, egoridze74 commented on models/Formula.cpp
> +  this->elements = elements;
Мб тогда будет лучше передавать ссылку на массив, а при присваивании его разыменовывать?

2024-06-15 23:30 UTC, egoridze74 commented on models/Control_element.cpp
> +    elem.set_id(sqlite3_column_int64(statement, 0));
Не совсем понял, про что ты. Я же тут просто пустой объект с помощью конструктора умолчания создаю (сори, мб туплю люто).

2024-06-16 22:49 UTC, egoridze74 commented on models/Control_element.cpp
> +        reinterpret_cast<const char*>(sqlite3_column_text(statement, 1)));
вот я что-то не вкурил, во что кастить тогда. Или не кастить вообще. Я всегда за мечников играл, кастингом спеллов никогда не занимался

2024-06-16 23:01 UTC, diduk001 requested changes

2024-06-16 23:01 UTC, diduk001 commented on include/db_utils.h
> +  return sqlite3_last_insert_rowid(db_conn);
А как нам поможет sqlite3_last_insert_rowid? Кажется, тут надо полноценную проверку устроить и залогировать, если что-то пошло не так

2024-06-16 23:01 UTC, diduk001 commented on include/db_utils.h
> +  sqlite3_step(statement);
Почему не sqlite3_exec?

2024-06-16 23:01 UTC, diduk001 commented on models/Control_element.cpp
> +    elem.set_id(sqlite3_column_int64(statement, 0));
elem.set_id(std::move(statement, 0));

2024-06-16 23:01 UTC, diduk001 commented on models/Control_element.cpp
> +bool Control_element::operator==(const Control_element& other) const {
Ну кажется скорее нужно

2024-06-16 23:01 UTC, diduk001 commented on models/Control_element.cpp
> +  output = "Название: " + this->get_name() +
- Для сообщений и их форматирования есть специальный неймспейс в consts, сюда выводить это все нельзя
- Здесь это нужно скорее для логов
- В CLion стоит проверить C++ version где-то в настройках проекта

2024-06-16 23:01 UTC, diduk001 commented on models/Formula.cpp
> +  this->elements = elements;
тогда будет два указателя на один и тот же массив, это тоже не очень круто

2024-06-17 09:33 UTC, egoridze74 commented on include/db_utils.h
> +  sqlite3_step(statement);
Попробовал, exec как аргумент принимает строку, а когда мы используем метод bind, то меняем не строку, а сам statement. В отличие от exec, step как аргумент принимает именно указатель на statement.

2024-06-17 09:45 UTC, egoridze74 commented on include/db_utils.h
> +  return sqlite3_last_insert_rowid(db_conn);
Вообще, на нём держится вся нумерация айишников, потому что только с помощью него мы меняем id у объектов этого класса (есть ещё конструктор с id и всеми другими параметрами, но мы его не используем)

2024-06-18 17:33 UTC, diduk001 requested changes

2024-06-18 17:33 UTC, diduk001 commented on include/utils.h
> +bool cmp_weights(const Control_element &e1, const Control_element &e2) {
https://en.cppreference.com/w/cpp/utility/functional/greater

2024-06-18 17:33 UTC, diduk001 commented on models/Control_element.cpp
> +Control_element::Control_element() {
давай в .h и =default

2024-06-18 17:33 UTC, diduk001 commented on models/Control_element.cpp
> +Control_element::Control_element(const std::string& name, float weight,
давай в .h и через 
`a(int field_) : field(field_)`

2024-06-18 17:33 UTC, diduk001 commented on models/Control_element.cpp
> +Control_element::Control_element(size_t id, const std::string& name,
давай в .h и через
`a(int field_) : field(field_)`

2024-06-18 17:33 UTC, diduk001 commented on models/Control_element.cpp
> +Control_element::Control_element(size_t id) {
давай в .h и через
a(int field_) : field(field_)

2024-06-18 17:33 UTC, diduk001 commented on models/Control_element.cpp
> +Control_element::Control_element(const Control_element& other) {
давай в .h

2024-06-18 17:33 UTC, diduk001 commented on models/Control_element.cpp
> +      this->get_name(), std::to_string(this->get_weight()),
а `std::to_string` нужен?

2024-06-18 17:33 UTC, diduk001 commented on models/Control_element.cpp
> +      (this->get_blocking() == 1 ? "yes" : "no"), this->get_description());
можно без `==`

2024-06-18 17:33 UTC, diduk001 commented on models/Formula.cpp
> +    result.push_back(elem);
давай здесь в сторону emplace_back подумаем

2024-06-18 17:33 UTC, diduk001 commented on models/Formula.cpp
> +void Formula::set_elements(std::vector<Control_element>* elements) {
давай тут используем move

2024-06-18 17:33 UTC, diduk001 commented on models/Formula.cpp
> +  float unk_weight_sum = 0;
что значит unk? измени название пж

2024-06-18 17:33 UTC, diduk001 commented on models/Formula.cpp
> +  for (auto it = elems.begin(); it != elems.end(); it++)
1) почему нельзя `for (const auto& elem : elems)`?
2) если нельзя, вместо разыменования, используй ->

2024-06-18 17:33 UTC, diduk001 commented on models/Formula.cpp
> +  std::vector<Control_element> elems = this->elements;
происходит копирование, иди сразу по this->elements

2024-06-18 19:23 UTC, egoridze74 commented on models/Control_element.cpp
> +Control_element::Control_element(size_t id) {
тут это вроде не нужно, мы ведь в этом конструкторе из бд грузим

2024-06-18 23:30 UTC, diduk001 requested changes

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +#define MAX_ELEMENT_NAME 100
в constants

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +enum class CE_state {
в state_utils

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +std::unordered_map<int64_t, CE_state> user_CE_states;
в state_utils

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +void set_CE_state(int64_t userId, CE_state state) {
в state_utils

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +  db::create_working_db();
давай init и close в create_working занесем

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +  TgBot::InlineKeyboardMarkup::Ptr keyboard_blocking(
в constants

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +      const std::regex is_float(R"(\d+\.\d+)");
в constants

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +            std::format("Название: {}\n"
в constants формат

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +        bot.getApi().sendMessage(userId, messages::is_right, NULL, 0,
NULL, 0 -> nullptr

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
> +      int64_t userId = query->message->chat->id;
мб user_id вне условий получать?

2024-06-18 23:30 UTC, diduk001 commented on src/main.cpp
>        return;
return необязателен

2024-06-18 23:30 UTC, diduk001 commented on models/Formula.cpp
> +    result.emplace_back(elem);
давай emplace полей сделаем, а не готового объекта

2024-06-19 10:17 UTC, closed without merging